#!/bin/bash

# INPUT PARAMETERS ####################################################

target=$1
usrmdl=$2

# DIRECTORIES #########################################################

GAPPdir="/home/kirtimaan/git-repos/GAPP/"
SCRPdir=$GAPPdir"scripts"
MDLSdir=$GAPPdir"/src/F/core/mdls"

tempdir=$GAPPdir"src/F/template/"
maindir=$GAPPdir"src/F/driver_code/"
coredir=$GAPPdir"src/F/core/"
builddir=$GAPPdir"build/"
##inputdir=$GAPPdir"bin/"
inputdir=""


# MODEL ARRAY #########################################################

cd $MDLSdir

mdlsf=(*.f)
mdls=()
nmdl=0

for mdlf in ${mdlsf[*]}
do
    
   mdls[$nmdl]=${mdlf%%.f}         
   nmdl=$nmdl+1

done

cd ${GAPPdir}bin/

# FUNCTIONS ###########################################################

clean() {

   make clean
   rm -rf *.o *.fit *.pull *.template~

}

#----------------------------------------------------------------------

mkfit() {

   if [ $usrmdl ]
   then

      sed 's/MODELNAME/'$usrmdl'/' ${tempdir}template_chi2.f > ${coredir}chi2.f
      sed 's/MODELNAME/'$usrmdl'/' ${tempdir}template_fit.f  > ${maindir}fit.f
      make fit
      mv fit $usrmdl.fit
      rm ${builddir}chi2.o ${builddir}fit.o

   else

      for mdl in ${mdls[*]}
      do
    
        sed 's/MODELNAME/'$mdl'/' ${tempdir}template_chi2.f.template > ${coredir}chi2.f
        sed 's/MODELNAME/'$mdl'/' ${tempdir}template_fit.f  > ${maindir}fit.f
        make fit
        mv fit $mdl.fit
        rm ${builddir}chi2.o ${builddir}fit.o
 
      done

   fi

}

#----------------------------------------------------------------------

fit() {

   summary=$GAPPdir/summary.out
    
   if [ -e $summary ]; then rm $summary; fi

   if [ $usrmdl ]
   then

      sed 's/MODELNAME/'$usrmdl'/' ${tempdir}template_smfit.dat > ${inputdir}smfit.dat
      echo "Fitting the ["$usrmdl"] model"
      nice ./$usrmdl.fit

   else

      for mdl in ${mdls[*]}
      do

         sed 's/MODELNAME/'$mdl'/' ${tempdir}template_smfit.dat > ${inputdir}smfit.dat
         echo "Fitting the ["$mdl"] model"
         nice ./$mdl.fit
 
      done

   fi

}

# COMPILE COMMANDS ####################################################

case "$target" in

   clean) clean
   ;;
   mkfit) mkfit 
   ;;
   fit)   fit 
   ;;
   all)   clean
          mkfit
          fit          
   ;;
   *)     echo "Options: 'mkfit', 'fit', 'clean' and 'all'" 
   ;;

esac

#######################################################################

exit 0
